FROM python:3.9-slim

WORKDIR /app

COPY src/requirements.txt ./requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN mkdir -p /app/src/models /app/src/data

WORKDIR /app/src

CMD ["python", "main.py"]
